CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(100) NOT NULL,
    nombre_completo VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    especie VARCHAR(50),
    raza VARCHAR(50),
    fecha_nacimiento DATE,
    peso DOUBLE,
    notas VARCHAR(255),
    foto VARCHAR(255),
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_mascota_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS historial_medico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT,
    titulo VARCHAR(255),
    descripcion VARCHAR(2000),
    fecha DATE,
    proxima_fecha DATE,
    veterinario VARCHAR(255),
    tipo VARCHAR(100),
    medicacion VARCHAR(255),
    CONSTRAINT fk_historial_mascota
        FOREIGN KEY (mascota_id) REFERENCES mascotas(id)
);

INSERT INTO usuarios (nombre_usuario, contrasena_hash, nombre_completo)
VALUES (
    'profesor',
    '$2b$12$iErvFqT6xUvTcW8kaPkGseZ7RwUb/OfgQ3Y9ytohkWFyCm..LY9gO',
    'Usuario Profesor'
);
