CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(100) NOT NULL,
    nombre_completo VARCHAR(100)
);

INSERT INTO usuarios (nombre_usuario, contrasena_hash, nombre_completo)
VALUES (
    'profesor',
    '$2b$12$iErvFqT6xUvTcW8kaPkGseZ7RwUb/OfgQ3Y9ytohkWFyCm..LY9gO',
    'Usuario Profesor'
);
